#!/bin/bash

# add_comment (bash script): adds a text remark to a text-based file
#  example usage at shell prompt:
#   $ add_comment notes "#todo Call that cool person I met at that party"
#  description of behavior:
#   leaves an extra newline between the new remark and the existing content

file="$1"
msg="$2"
if [[ `tail -n 1 "$file"` ]];   then echo "" | cat >> "$file";   fi
echo -e "$msg" | cat >> "$file"

